export const BLOG_LIST_REQUEST="BLOG_LIST_REQUEST"
export const BLOG_LIST_SUCCESS="BLOG_LIST_SUCCESS"
export const BLOG_LIST_FAIL="BLOG_LIST_FAIL"

export const BLOG_DETAIL_REQUEST="BLOG_DETAIL_REQUEST"
export const BLOG_DETAIL_SUCCESS="BLOG_DETAIL_SUCCESS"
export const BLOG_DETAIL_FAIL="BLOG_DETAIL_FAIL"

export const BLOG_LIKE_REQUEST="BLOG_LIKE_REQUEST"
export const BLOG_LIKE_SUCCESS="BLOG_LIKE_SUCCESS"
export const BLOG_LIKE_FAIL="BLOG_LIKE_FAIL"

export const BLOG_DISLIKE_REQUEST="BLOG_DISLIKE_REQUEST"
export const BLOG_DISLIKE_SUCCESS="BLOG_DISLIKE_SUCCESS"
export const BLOG_DISLIKE_FAIL="BLOG_DISLIKE_FAIL"