export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL"

export const PRODUCT_FEATURED_REQUEST="PRODUCT_FETURED_REQUEST"
export const PRODUCT_FEATURED_SUCCESS="PRODUCT_FETURED_SUCCESS"
export const PRODUCT_FEATURED_FAIL="PRODUCT_FEATURED_FAIL"

export const PRODUCT_BEST_REQUEST="PRODUCT_BEST_REQUEST"
export const PRODUCT_BEST_SUCCESS="PRODUCT_BEST_SUCCESS"
export const PRODUCT_BEST_FAIL="PRODUCT_BEST_FAIL"

export const PRODUCT_DETAIL_REQUEST="PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL"

export const PRODUCT_WISHLIST_REQUEST="PRODUCT_WISHLIST_REQUEST"
export const PRODUCT_WISHLIST_SUCCESS="PRODUCT_WISHLIST_SUCCESS"
export const PRODUCT_WISHLIST_FAIL="PRODUCT_WISHLIST_FAIL"

export const PRODUCT_RELATED_REQUEST="PRODUCT_RELATED_REQUEST"
export const PRODUCT_RELATED_SUCCESS="PRODUCT_RELATED_SUCCESS"
export const PRODUCT_RELATED_FAIL="PRODUCT_RELATED_FAIL"

export const PRODUCT_CREATE_REVIEW_REQUEST="PRODUCT_CREATE_REVIEW_REQUEST"
export const PRODUCT_CREATE_REVIEW_SUCCESS="PRODUCT_CREATE_REVIEW_SUCCESS"
export const PRODUCT_CREATE_REVIEW_FAIL="PRODUCT_CREATE_REVIEW_FAIL"
export const PRODUCT_CREATE_REVIEW_RESET="PRODUCT_CREATE_REVIEW_RESET"